[package]
name = "rust-glium-triangle"
version = "0.1.0"
authors = ["Arthur Dev <73297053+ArthurDeveloper@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.1"
